### ISSUE TITLE
这个有文档吗

### ISSUE THREAD

**Issue by huang1229** [Nomination-NRB/ImageProcess#1]

**Comment by Nomination-NRB** [comment]
> _No description provided._

README.md就是整合的完整的使用文档了

**Comment by huang1229** [comment]
就是那个图片修复是利用什么算法呢，看不太懂


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Nomination-NRB/ImageProcess"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月13日(星期四) 下午2:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Nomination-NRB/ImageProcess] 这个有文档吗 (Issue #1)





  
No description provided.
  
README.md就是整合的完整的使用文档了

**Comment by Nomination-NRB** [comment]
> 就是那个图片修复是利用什么算法呢，看不太懂
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Nomination-NRB/ImageProcess" ***@***.***&gt;; 发送时间:&nbsp;2023年4月13日(星期四) 下午2:21 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Nomination-NRB/ImageProcess] 这个有文档吗 (Issue #1) No description provided. README.md就是整合的完整的使用文档了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

所有的图片处理原函数都在ImageProcess/DjangoRestframework/lib/manage/imageProcess.py文件下，里面有很多图像滤波，我不知道你说的图片修复具体指的是哪一个滤波，你可以直接去查某个滤波的算法原理，再用python实现就行了，我和我同学也是去找相应的算法原理再自己查资料实现的

**Comment by huang1229** [comment]
就是那个图片修复是利用什么算法呢，看不太懂
这个一个工程项目吗，想看一下具体的模块，因为这学期我想做一个去噪，超分的系统，想参考一下


------------------ 原始邮件 ------------------
发件人:                                                                                                                        "Nomination-NRB/ImageProcess"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月13日(星期四) 下午2:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Nomination-NRB/ImageProcess] 这个有文档吗 (Issue #1)





  
No description provided.
  
README.md就是整合的完整的使用文档了

**Comment by Nomination-NRB** [comment]
> 就是那个图片修复是利用什么算法呢，看不太懂 这个一个工程项目吗，想看一下具体的模块，因为这学期我想做一个去噪，超分的系统，想参考一下
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "Nomination-NRB/ImageProcess" ***@***.***&gt;; 发送时间:&nbsp;2023年4月13日(星期四) 下午2:21 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Nomination-NRB/ImageProcess] 这个有文档吗 (Issue #1) No description provided. README.md就是整合的完整的使用文档了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

imageProcess.py里面包含了本项目所有的图片处理函数，你可以**自己读取图片**然后**调用**里面的**函数**来达到去噪等其他功能

**Comment by huang1229** [comment]
好的，谢谢，我再研究一下这些函数，今早看了好久




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Nomination-NRB/ImageProcess"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月13日(星期四) 下午2:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Nomination-NRB/ImageProcess] 这个有文档吗 (Issue #1)





  
就是那个图片修复是利用什么算法呢，看不太懂 这个一个工程项目吗，想看一下具体的模块，因为这学期我想做一个去噪，超分的系统，想参考一下
 …
 ------------------ 原始邮件 ------------------ 发件人: "Nomination-NRB/ImageProcess" @.&gt;; 发送时间:&nbsp;2023年4月13日(星期四) 下午2:21 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [Nomination-NRB/ImageProcess] 这个有文档吗 (Issue #1) No description provided. README.md就是整合的完整的使用文档了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
imageProcess.py里面包含了本项目所有的图片处理函数，你可以自己读取图片然后调用里面的函数来达到去噪等其他功能

**Comment by Nomination-NRB** [comment]
> 好的，谢谢，我再研究一下这些函数，今早看了好久
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Nomination-NRB/ImageProcess" ***@***.***&gt;; 发送时间:&nbsp;2023年4月13日(星期四) 下午2:46 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Nomination-NRB/ImageProcess] 这个有文档吗 (Issue #1) 就是那个图片修复是利用什么算法呢，看不太懂 这个一个工程项目吗，想看一下具体的模块，因为这学期我想做一个去噪，超分的系统，想参考一下 … ------------------ 原始邮件 ------------------ 发件人: "Nomination-NRB/ImageProcess" @.&gt;; 发送时间:&nbsp;2023年4月13日(星期四) 下午2:21 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [Nomination-NRB/ImageProcess] 这个有文档吗 (Issue #1) No description provided. README.md就是整合的完整的使用文档了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt; imageProcess.py里面包含了本项目所有的图片处理函数，你可以自己读取图片然后调用里面的函数来达到去噪等其他功能 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

最好就是自己实际调用函数，来处理本地图片，这样能比较好的理解它的原理（我将问题close了哦）

**Comment by huang1229** [comment]
好的呢，谢啦~




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月13日(星期四) 下午2:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Nomination-NRB/ImageProcess] 这个有文档吗 (Issue #1)





  
好的，谢谢，我再研究一下这些函数，今早看了好久
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Nomination-NRB/ImageProcess" @.&gt;; 发送时间:&nbsp;2023年4月13日(星期四) 下午2:46 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [Nomination-NRB/ImageProcess] 这个有文档吗 (Issue #1) 就是那个图片修复是利用什么算法呢，看不太懂 这个一个工程项目吗，想看一下具体的模块，因为这学期我想做一个去噪，超分的系统，想参考一下 … ------------------ 原始邮件 ------------------ 发件人: "Nomination-NRB/ImageProcess" @.&gt;; 发送时间:&nbsp;2023年4月13日(星期四) 下午2:21 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [Nomination-NRB/ImageProcess] 这个有文档吗 (Issue #1) No description provided. README.md就是整合的完整的使用文档了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; imageProcess.py里面包含了本项目所有的图片处理函数，你可以自己读取图片然后调用里面的函数来达到去噪等其他功能 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt;
  
最好就是自己实际调用函数，来处理本地图片，这样能比较好的理解它的原理（我将问题close了哦）
